import { Fustat, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "react-loading-skeleton/dist/skeleton.css";
import { ConversationProvider } from "@/contexts/ConversationContext";
import DailyProviderClient from "@/components/providers/DailyProviderClient";

const inter = Inter({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  fallback: ['sans-serif'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ConversationProvider>
          <DailyProviderClient>
            <Toaster />
            {children}
          </DailyProviderClient>
        </ConversationProvider>
      </body>
    </html>
  );
}
